---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms
  namespace: chewedfeed
  labels:
    name: cms
    app: cms
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: cms
  template:
    metadata:
      labels:
        app: cms
        name: cms
    spec:
      hostAliases:
        - ip: "192.168.1.121"
          hostnames:
            - "db.chewed-k8s.net"
      imagePullSecrets:
        - name: docker-registry-secret
      containers:
        - name: cms
          image: containers.chewed-k8s.net/chewedfeed/soon-cms:latest
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
          ports:
            - containerPort: 3001
          env:
            - name: RDS_HOSTNAME
              value: "db.chewed-k8s.net"
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: coming-soon-token
                  key: vault-token
---
apiVersion: v1
kind: Service
metadata:
  name: cms
  namespace: chewedfeed
  labels:
    app: cms
    name: cms
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3001
  selector:
    app: cms
