---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms
  namespace: chewedfeed
  labels:
    name: cms
    app: cms
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: cms
  template:
    metadata:
      labels:
        app: cms
        name: cms
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: cms
          image: containers.chewedfeed.com/chewedfeed/soon-cms:latest
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
          ports:
            - containerPort: 3000
          env:
            - name: RDS_HOSTNAME
              value: "kube-nas.home.develbox.info"
---
apiVersion: v1
kind: Service
metadata:
  name: cms
  namespace: chewedfeed
  labels:
    app: cms
    name: cms
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: cms
